### ISSUE TITLE
Helpscout Modal zindex

### ISSUE THREAD

**Issue by juan0087** [evertiro/Beacon-For-Helpscout#1]
Hello there,

I need to add a higher zindex to the modal but I noticed there are no options on the setting page. What would be the best way to change the default zindex?

Thank in advance!

**Comment by evertiro** [comment]
While we can sort of override the z-index for the button itself, we can't override the form dynamically due to the way it loads. You can manually override it by targeting `#hs-beacon iframe` in your CSS.
