### ISSUE TITLE
Add JS for Open-Close-Toggle button support

### ISSUE THREAD

**Issue by rumspeed** [evertiro/Beacon-For-Helpscout#2]
If you add these utility functions ([found here](http://developer.helpscout.net/beacons/javascript-api/)), buttons can be added that Open, Close and Toggle the HelpScout Beacon.

`jQuery('#btn-open').click(function() {
  HS.beacon.open();
});`
`jQuery('#btn-close').click(function() {
  HS.beacon.close();
});`
`jQuery('#btn-toggle').click(function() {
  HS.beacon.toggle();
});`

`<button id="btn-open">Open Beacon</button>`
`<button id="btn-close">Close Beacon</button>`
`<button id="btn-toggle">Toggle Beacon</button>`

The JS must be added to `beacon.js` and `beacon.min.js` files so the button code can work properly.

**Comment by evertiro** [comment]
Added in 1.2.0, though I'm using `beacon-open`, etc to prevent possible conflicts.
