### ISSUE TITLE
Translation load_textdomain

### ISSUE THREAD

**Issue by junglewp** [evertiro/Beacon-For-Helpscout#3]
Hello,

I am very happy to have found your Plugin! Thanks for  your contribution.

By the way I was trying to translate your plugin but I couldn't figure out how to use my generated .mo file.

I created a /languages/ directory within the plugin installation directory and reamed the file as follow : beacon-for-helpscout-fr_FR.mo but it didn't work.
I also tried moving my .mo to /wp-content/languages/beacon-for-helpscout/ and renamed the .mo as follow fr_FR.mo and beacon-for-helpscout-fr_FR.mo without success.

Please can you help me do it correctly ?

The best,
Franck

**Comment by evertiro** [comment]
Can you post the language files? That looks like it should be correct.
